CyberBlog.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CyberBlog.DataAccess.Services;
using CyberBlog.ViewModel;
using System.Threading.Tasks;
using CyberBlog.Web.AuthProvider;

namespace CyberBlog.Web.Controllers
{
    public class AdminController : Controller
    {
		private PostService _postService;
		private IAuthProvider _authProvider;

		public AdminController()
		{
			_postService = new PostService();
			_authProvider = new AuthProvider.AuthProvider();
		}

		/// <summary>
		/// Return collection of tags and categories. Works for typeahead and categories drop down list.
		/// </summary>
		/// <returns></returns>
		[Authorize]
        public ActionResult List()
        {
			var tags = _postService.Tags();
			var categories = _postService.Categories();
			CategoriesTagsList list = new CategoriesTagsList();
			list.Categories = categories;
			list.Tags = tags;
			return View("List", list);
        }

		/// <summary>
		/// return collection of posts for data grid
		/// </summary>
		/// <param name="param"></param>
		/// <returns></returns>
		[HttpGet]
		public JsonResult Posts(DataTablePager param)
		{
			string Status = "";
			string Tags = "";
			int i = 1;
			List<string[]> dataList = new List<string[]>();
			IEnumerable<CyberBlog.BlogEntity.Post> filterdPosts;
			List<CyberBlog.BlogEntity.Post> allPosts;
			var sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);
			var sortDirection = Request["sSortDir_0"];
			allPosts = _postService.Posts();
			if (!string.IsNullOrEmpty(param.sSearch))
			{
				allPosts = allPosts.Where(x => x.Title.Contains(param.sSearch) || x.ShortDesc.Contains(param.sSearch) || x.FullDesc.Contains(param.sSearch) || x.Category.Name.Contains(param.sSearch)).ToList();
			}
			else
			{
				//allEntries = _service.GetAllEntries(BlogId).ToList(); ;
			}
			switch (sortColumnIndex)
			{
				case 1: //Sorted by title
					if (sortDirection == "asc")
					{
						allPosts = allPosts.OrderBy(x => x.Title).ToList();
					}
					else
					{
						allPosts = allPosts.OrderByDescending(x => x.Title).ToList();
					}
					break;
				case 2: //Sorted by category
					if (sortDirection == "asc")
					{
						allPosts = allPosts.OrderBy(x => x.Category.Name).ToList();
					}
					else
					{
						allPosts = allPosts.OrderByDescending(x => x.Category.Name).ToList();
					}
					break;
				case 5: //Sorted by date
					if (sortDirection == "asc")
					{
						allPosts = allPosts.OrderBy(x => x.PostedDate).ToList();
					}
					else
					{
						allPosts = allPosts.OrderByDescending(x => x.PostedDate).ToList();
					}
					break;

			}

			filterdPosts = allPosts;
			var displayEntries = filterdPosts.Skip(param.iDisplayStart).Take(param.iDisplayLength);
			foreach (var entry in displayEntries)
			{
				switch (entry.Published)
				{
					case true:
						Status = "Published";
						break;
					case false:
						Status = "Draft";
						break;
				}
				foreach (var tag in entry.Tags)
				{
					if (i == entry.Tags.Count)
					{
						Tags += tag.Name;
					}
					else
					{
						Tags += tag.Name + ", ";
					}
					i++;
				}
				dataList.Add(new[] { entry.Id.ToString(), entry.Title,entry.Category.Name, Tags, entry.Author, entry.PostedDate.ToString("dd/MM/yyyy"), Status });
				Tags = "";
				i = 1;
			}
			return Json(new
			{
				sEcho = param.sEcho,
				iTotalRecords = allPosts.Count,
				iTotalDisplayRecords = filterdPosts.ToList().Count,
				aaData = dataList
			},
				JsonRequestBehavior.AllowGet);
		}

		/// <summary>
		/// return a post based on paticular id
		/// </summary>
		/// <param name="postId"></param>
		/// <returns></returns>
		[HttpGet]
		[Authorize]
		public JsonResult Post(int postId)
		{
			PostViewModel post = new PostViewModel();
			List<TagViewModel> tagList = new List<TagViewModel>();
			var result = _postService.Post(postId);
			if (result != null)
			{
				post.PostId = result.Id;
				post.Author = result.Author;
				post.Title = result.Title;
				post.ShortDesc = result.ShortDesc;
				post.FullDesc = result.FullDesc;
				post.Published = result.Published;
				post.Category = result.Category.Name;
				post.CategoryId = result.CategoryId;
				post.UrlSlug = result.UrlSlug;
				foreach (var item in result.Tags)
				{
					TagViewModel tag = new TagViewModel();
					tag.Tag = item.Name;
					tagList.Add(tag);
				}
				post.Tags = tagList;
			}
			return Json(post, JsonRequestBehavior.AllowGet);
		}

		/// <summary>
		/// save a modified post
		/// </summary>
		/// <param name="post"></param>
		/// <returns></returns>
		[HttpPost]
		[Authorize]
		public JsonResult Save(PostViewModel post)
		{
			bool isSaved = false;
			if (ModelState.IsValid)
			{
				if (post.Tags != null && post.Tags.Count > 0)
				{
					var tags = _postService.Tags();
					foreach (var tag in post.Tags)
					{
						var _result = tags.Where(x => x.Tag.ToLower() == tag.Tag.ToLower()).FirstOrDefault();
						if (_result != null) //exsiting tag
						{
							tag.TagId = _result.TagId;
						}
						else //new tag
						{
							tag.TagId = 0;
						}
					}
					isSaved = _postService.SavePost(post);
				}
				else
				{
					isSaved = _postService.SavePost(post);
				}
			}
			else
			{
				/*
				foreach (ModelState modelState in ViewData.ModelState.Values)
				{
					foreach (ModelError error in modelState.Errors)
					{
						var info = error.ErrorMessage;
					}
				}
				 */
				isSaved= false;
			}
			
			return Json(isSaved);
		}

		/// <summary>
		/// delete a post
		/// </summary>
		/// <param name="id"></param>
		/// <returns></returns>
		[HttpDelete]
		[Authorize]
		public JsonResult DeletePost(int id = 0)
		{
			if (id >0)
			{
				return Json(_postService.DeletePost(id));
			}
			else
			{
				return Json(false);
			}
		}

		/// <summary>
		/// show writing post view
		/// </summary>
		/// <returns></returns>
		[Authorize]
		public ActionResult Write()
		{
			var tags = _postService.Tags();
			var categories = _postService.Categories();
			CategoriesTagsList list = new CategoriesTagsList();
			list.Categories = categories;
			list.Tags = tags;
			return View("Write", list);
		}

		/// <summary>
		/// Add a new post.
		/// </summary>
		/// <param name="post"></param>
		/// <returns></returns>
		[HttpPost]
		[Authorize]
		public JsonResult AddPost(PostViewModel post)
		{
			bool isSaved = false;
			if (ModelState.IsValid)
			{
				if (post.Tags != null && post.Tags.Count > 0)
				{
					var tags = _postService.Tags();
					foreach (var tag in post.Tags)
					{
						var _result = tags.Where(x => x.Tag.ToLower() == tag.Tag.ToLower()).FirstOrDefault();
						if (_result != null) //exsiting tag
						{
							tag.TagId = _result.TagId;
						}
						else //new tag
						{
							tag.TagId = 0;
						}
					}
					isSaved = _postService.AddPost(post);
				}
				else
				{
					isSaved = _postService.AddPost(post);
				}
			}
			else
			{
				/*
				foreach (ModelState modelState in ViewData.ModelState.Values)
				{
					foreach (ModelError error in modelState.Errors)
					{
						var info = error.ErrorMessage;
					}
				}
				 */
				isSaved = false;
			}
			return Json(isSaved);
		}

		/// <summary>
		/// shows collection of categories
		/// </summary>
		/// <returns></returns>
		[Authorize]
		public ActionResult Category()
		{
			var categories = _postService.Categories();
			return View(categories);
		}

		/// <summary>
		/// Show collection of tags
		/// </summary>
		/// <returns></returns>
		[Authorize]
		public ActionResult Tag()
		{
			var tags = _postService.Tags();
			return View(tags);
		}

		/// <summary>
		/// create a new tag
		/// </summary>
		/// <param name="tag">new tag name</param>
		/// <returns>return new tag id</returns>
		[HttpPost]
		[Authorize]
		public int NewTag(string tag)
		{
			int tagId = 0;
			if (string.IsNullOrEmpty(tag))
			{
				return tagId;
			}
			else
			{
				tagId=_postService.NewTag(tag.ToLower());
				if(tagId>0)
				{
					return tagId;
				}
				else
				{
					return 0;
				}
			}
		}

		/// <summary>
		/// update a tag
		/// </summary>
		/// <param name="tag">tag name</param>
		/// <param name="id">tag id</param>
		/// <returns></returns>
		[HttpPut]
		[Authorize]
		public JsonResult UpdateTag(string tag,int tagId)
		{
			if (string.IsNullOrEmpty(tag) || tagId == 0)
			{
				return Json(false);
			}
			else
			{
				return Json(_postService.UpdateTag(tag,tag,tagId));
			}
		}

		/// <summary>
		/// delete a tag by id
		/// </summary>
		/// <param name="id">tag id</param>
		/// <returns></returns>
		[HttpDelete]
		[Authorize]
		public JsonResult DeleteTag(int tagId)
		{
			if (tagId == 0)
			{
				return Json(false);
			}
			else
			{
				return Json(_postService.DeleteTag(tagId));
			}
		}

		/// <summary>
		/// add a new category
		/// </summary>
		/// <param name="category"></param>
		/// <returns>the new category's id</returns>
		[HttpPost]
		[Authorize]
		public int NewCategory(string category)
		{
			if (string.IsNullOrEmpty(category))
			{
				return 0;
			}
			else
			{
				return _postService.NewCategory(category, category);
			}
		}

		/// <summary>
		/// update a category
		/// </summary>
		/// <param name="category">new name</param>
		/// <param name="categoryId">id</param>
		/// <returns></returns>
		[HttpPost]
		[Authorize]
		public JsonResult UpdateCategory(string category,int categoryId)
		{
			if (category == null)
			{
				return Json(false);
			}
			else
			{

				return Json(_postService.UpdateCategory(category,category,categoryId));
			}
		}

		/// <summary>
		/// delete a category by id
		/// </summary>
		/// <param name="categoryId"></param>
		/// <returns></returns>
		[HttpDelete]
		[Authorize]
		public JsonResult DeleteCategory(int categoryId)
		{
			if (categoryId == 0)
			{
				return Json(false);
			}
			else
			{

				return Json(_postService.DeleteCategory(categoryId));
			}
		}

		/// <summary>
		/// Return the login page
		/// </summary>

CyberBlog.Web/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CyberBlog.DataAccess.Services;
using CyberBlog.BlogHelper;

namespace CyberBlog.Web.Controllers
{
	public class PostController : Controller
	{
		
		private  PostService _postService;
		private int pageSize;

		public PostController()
		{
			pageSize = Helper.GetAppSettings().PageSize;
			_postService = new PostService();
		}

		/// <summary>
		/// Return the list page with latest posts.
		/// </summary>
		/// <param name="pageNo">pagination number</param>
		/// <returns></returns>
		public ActionResult PostsList(int pageNo = 1)
		{
			ViewBag.Title = "";
			var viewModel = _postService.Posts(pageNo,pageSize);
			return View("PostsList",viewModel);
		}

		/// <summary>
		/// Return a particular post based on the puslished year, month and url slug.
		/// </summary>
		/// <param name="year">Published year</param>
		/// <param name="month">Published month</param>
		/// <param name="title">Url slug</param>
		/// <returns></returns>
		public ActionResult Post(string year,string month,string title)
		{
			var viewModel = _postService.Post(year,month,title);
			ViewBag.Title = viewModel.Title;
			return View(viewModel);
		}

		/// <summary>
		/// Return collection of categories.
		/// </summary>
		/// <returns></returns>
		
		public ActionResult Categories()
		{
			var viewModel = _postService.Categories();
			return PartialView("_Categories",viewModel);
		}

		/// <summary>
		/// Return collection of posts belongs to a particular category.
		/// </summary>
		/// <param name="category">Category's url slug</param>
		/// <param name="catPageNo">Page index</param>
		/// <returns></returns>
		public ActionResult Category(string category, int catPageNo= 1)
		{
			CyberBlog.ViewModel.PostsListViewModel viewModel = _postService.PostsByCategory(category, catPageNo, pageSize);
			foreach (var item in viewModel.Posts)
			{
				ViewBag.Title = item.Category.Name + " Archives - ";
				ViewBag.SubTitle = "Categories - " + item.Category.Name;
				break;
			}
			return View("PostsList",viewModel);
		}

		/// <summary>
		/// Return collection of tags.
		/// </summary>
		/// <returns></returns>
		
		public ActionResult Tags()
		{
			var viewModel = _postService.ValidTags();
			return PartialView("_Tags",viewModel);
		}
		

		/// <summary>
		/// Return collection of posts belongs to a particular tag.
		/// </summary>
		/// <param name="tag">Tag's url slug</param>
		/// <param name="tagPageNo">Page index</param>
		/// <returns></returns>
		public ActionResult Tag(string tag, int tagPageNo = 1)
		{
			string _tag;
			ViewBag.Title = null;
			var viewModel = _postService.PostsByTag(tag, tagPageNo, pageSize);
			foreach (var item in viewModel.Posts)
			{
				_tag = item.Tags.Where(x => x.UrlSlug.ToLower() == tag.ToLower()).Single().Name;
				ViewBag.Title =_tag+" Archives - ";
				ViewBag.SubTitle = "Tags - " +_tag;
				break;
			}
			return View("PostsList", viewModel);
		}

		/// <summary>
		/// Return the posts that matches the search term.
		/// </summary>
		/// <param name="term">search text</param>
		/// <param name="searchPageNo">Pagination number</param>
		/// <returns></returns>
		public ViewResult Search(string term, int searchPageNo = 1)
		{
			var viewModel = _postService.SearchPosts(term, searchPageNo, pageSize);
			ViewBag.Title = term + " - " + "Blog Search";
			ViewBag.SubTitle = "Search By - " + term;
			return View("PostsList",viewModel);
		}

	}
}

CyberBlog.Web/Views/Shared/_AdminLayout.cshtml
@{
	Layout = "~/Views/Shared/_SiteLayout.cshtml";
}
@*<link href="~/Scripts/DataTables-1.10.4/css/dataTables.bootstrap.css" rel="stylesheet" />
<link href="~/Scripts/Summernote/summernote.css" rel="stylesheet" />
<link href="~/Scripts/Bootstrap-Tagsinput/bootstrap-tagsinput.css" rel="stylesheet" />*@
@Styles.Render("~/Content/admin-css")
<div class="row">
	<div class="col-sm-12">
		<!-- Nav tabs -->
		<ul id="admin-tabs" class="nav nav-tabs">
			<li id="list" class="active"><a href='@Url.Action("List", "Admin")'>List</a></li>
			<li id="write"><a href="@Url.Action("Write","Admin")">Write</a></li>
			<li id="category"><a href="@Url.Action("Category", "Admin")">Categories</a></li>
			<li id="tag"><a href="@Url.Action("Tag","Admin")">Tags</a></li>
		</ul>
		<!-- Tab panes -->
		<div class="tab-content">
			@RenderBody()
		</div>
	</div>
</div>
@Scripts.Render("~/bundles/admin-js")
@*<script src="~/Scripts/DataTables-1.10.4/js/jquery.dataTables.min.js"></script>
<script src="~/Scripts/DataTables-1.10.4/js/dataTables.bootstrap.js"></script>
<script src="~/Scripts/Summernote/summernote.min.js"></script>
<script src="~/Scripts/bootstrap3-typeahead.min.js"></script>
<script src="~/Scripts/Bootstrap-Tagsinput/bootstrap-tagsinput.min.js"></script>*@
@RenderSection("Scripts", required: false)

CyberBlog.Web/Views/Shared/_Categories.cshtml
@model IEnumerable<CyberBlog.ViewModel.CategoryViewModel>
<h4 class="side-bar">Categories</h4>
<ul>
	@if (Model.Count() > 0)
	{
		foreach (var item in Model)
		{
			<li>
				<a href="/category/@item.UrlSlug">@item.Category</a><span class="badge pull-right">@item.Count</span>
			</li>
		}
	}
</ul>

CyberBlog.Web/Views/Shared/_Disqus.cshtml
@using CyberBlog.BlogHelper
@model CyberBlog.ViewModel.PostViewModel

<script type="text/javascript" defer="defer">
	/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
	var disqus_shortname = '@Helper.GetAppSettings().ShortName'; // required: replace example with your forum shortname
	var disqus_identifier = '@Request.Url';
	var disqus_title = '@Model.Title';
	var disqus_url = '@Request.Url.AbsoluteUri';
	//var disqus_developer = 1;

	/* * * DON'T EDIT BELOW THIS LINE * * */
	(function () {
		var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
		dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
		(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	})();
</script>

CyberBlog.Web/Views/Shared/_Loading.cshtml
<div id="loading" style="position: absolute; left: 50%; top: 50%; margin-left: -100px; margin-top: -50px; text-align: center; z-index: 99999;"></div>
<script>
	function showLoading() {
		$('#loading').html('<img src="/Images/loading.gif"/>');
	}

	function closeLoading() {
		$('#loading').html('');
	}
</script>

CyberBlog.Web/Views/Shared/_Pager.cshtml
@model CyberBlog.ViewModel.PostsListViewModel
@using CyberBlog.BlogHelper

@{
	int totalPosts=0;
	int currentPage=0;
	string url_pre,url_next;
	string action = ViewContext.RouteData.Values["action"].ToString().ToLower();
	totalPosts = Model.TotalPosts;
	int pageSize =Helper.GetAppSettings().PageSize;
	
	switch (action)
	{
		case"postslist":
			if (ViewContext.RouteData.Values["pageNo"] != null)
			{
				currentPage = ViewContext.RouteData.Values["pageNo"].ToString() != null ? int.Parse(ViewContext.RouteData.Values["pageNo"].ToString()) : 1;
			}
			else
			{
				currentPage = 1;
			}
			break;
		case "category":
			if (ViewContext.RouteData.Values["catPageNo"] != null)
			{
				currentPage = ViewContext.RouteData.Values["catPageNo"].ToString() != null ? int.Parse(ViewContext.RouteData.Values["catPageNo"].ToString()) : 1;
			}
			else
			{
				currentPage = 1;
			}
			break;
		case "tag":
			if (ViewContext.RouteData.Values["tagPageNo"] != null)
			{
				currentPage = ViewContext.RouteData.Values["tagPageNo"].ToString() != null ? int.Parse(ViewContext.RouteData.Values["tagPageNo"].ToString()) : 1;
			}
			else
			{
				currentPage = 1;
			}
			break;
		case "search":
			if (ViewContext.RouteData.Values["searchPageNo"] != null)
			{
				currentPage = ViewContext.RouteData.Values["searchPageNo"].ToString() != null ? int.Parse(ViewContext.RouteData.Values["searchPageNo"].ToString()) : 1;
			}
			else
			{
				currentPage = 1;
			}
			break;
		
	}
	
	//if (ViewContext.RouteData.Values["pageNo"] != null)
	//{
	//	currentPage = ViewContext.RouteData.Values["pageNo"].ToString() != null ? int.Parse(ViewContext.RouteData.Values["pageNo"].ToString()) : 1;
	//}
	//else
	//{
	//	currentPage = 1;
	//}
	
	
	var totalPages = Math.Ceiling((double)totalPosts / pageSize);
}
@if (currentPage > 0 || currentPage <= totalPages)
{
	var p = string.Format("{0}", currentPage - 1);
	var n = string.Format("{0}", currentPage + 1);

	switch (action)
	{
		case"tag":
			url_pre = Url.Action("tag", "Post", new { tagPageNo = p });
			url_next = Url.Action("tag", "Post", new { tagPageNo = n });
			break;
		case"category":
			url_pre = Url.Action("category", "Post", new { catPageNo = p });
			url_next = Url.Action("category", "Post", new { catPageNo = n });
			break;
		case"search":
			url_pre = Url.Action("search", "Post", new { term = String.Format("{0}", ViewContext.RouteData.Values["term"]), searchPageNo = p });
			url_next = Url.Action("search", "Post", new { term = String.Format("{0}", ViewContext.RouteData.Values["term"]), searchPageNo = n });
			break;
		default:
			url_pre = Url.Action("postslist", "Post", new { pageNo = p });
			url_next = Url.Action("postslist", "Post", new { pageNo = n });
			break;
	}
	<div class="nav-link row">
		<div class="col-sm-5">
			<a href="@url_pre" title="previous" class="btn btn-default pull-left" style="visibility:@(currentPage > 1 ? "visible" : "collapse")"><i class="fa fa-angle-left"></i> Previous</a>
		</div>
		<div class="col-sm-6 col-sm-offset-1">
			<a href="@url_next" title="Next" class="btn btn-default pull-right" style="visibility:@(currentPage < totalPages ? "visible" : "collapse")">Next <i class="fa fa-angle-right"></i></a>
		</div>
	</div>
}

CyberBlog.Web/Views/Shared/_PostLayout.cshtml
@{
	Layout = "~/Views/Shared/_SiteLayout.cshtml";
}
@RenderSection("Styles", false)
<div class="row">
	<div id="blog-left" class="col-sm-8">
		@RenderBody()
	</div>
	<div id="blog-right" class="col-sm-3 col-sm-offset-1">
		<div id="categories-nav">
			@{Html.RenderAction("Categories", "Post");}
		</div>
		<div id="tags-nav">
			@{Html.RenderAction("Tags", "Post");}
		</div>

	</div>
</div>
@RenderSection("Scripts", required: false)

CyberBlog.Web/Views/Shared/_Posts.cshtml
<div class="post-inner-content">

</div>

CyberBlog.Web/Views/Shared/_ShareThis.cshtml
@model CyberBlog.ViewModel.PostViewModel
<div class="social-likes social-likes_light" data-url="@Request.Url.AbsoluteUri" data-title="@Model.Title">
	<div class="facebook" title="Share link on Facebook">Facebook</div>
	<div class="twitter" title="Share link on Twitter">Twitter</div>
	<div class="plusone" title="Share link on Google+">Google+</div>
</div>

CyberBlog.Web/Views/Shared/_SiteLayout.cshtml
@using CyberBlog.BlogHelper;

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="robots" content="postslist, follow" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<link href="~/Content/google-font.css" rel="stylesheet" />
	@*<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>*@
	<!--[if lt IE 9]>
	<script src="Scripts/html5shiv.js"></script>
	<script src="Scripts/respond.min.js"></script>
	<![endif]-->
	<link rel="shortcut icon" href="@Url.Content("~/favicon.ico")" type="image/x-icon">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
	<title>@ViewBag.Title@Helper.GetAppSettings().BlogName</title>

	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/modernizr")
	@RenderSection("Styles", false)
</head>
<body>
	<!--[if lt IE 7]>
			<p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
			<p class="alert alert-danger">您正在使用<strong>旧版本</strong>浏览器. 您可以访问<a href="http://browsehappy.com/">更新您的浏览器</a> 这样可以正常使用本网站的功能。</p>
		<![endif]-->

	<div class="wrapper">
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					
				</div>

				<div id="navbar" class="collapse navbar-collapse">
					<div class="col-sm-9">
						<ul class="nav navbar-nav">
							<li><a href="/"><i class="fa fa-home"></i> Home</a></li>
							<li><a href="@Url.Action("about","about")"><i class="fa fa-info-circle"></i> About Me</a></li>
							<li class="hidden"><a href="@Url.Action("contact","contact")"><i class="fa fa-envelope"></i> Contact Me</a></li>
							<li><a href="@Url.Action("portfolio","portfolio")"><i class="fa fa-laptop"></i> Portfolio</a></li>
							@if (HttpContext.Current.User.Identity.IsAuthenticated)
							{
								<li><a href="@Url.Action("Logout","Admin")"><span class="fa fa-sign-out"></span> Logout</a></li>
							}

						</ul>
					</div>

					<div class="col-sm-3">
						<form class="navbar-form" role="form" action="@Url.Action("Search")" id="search-form" method="get">
							<div class="input-group">
								<input type="text" class="form-control" placeholder="Search" name="term" id="search-term" required>
								<div class="input-group-btn">
									<button class="btn btn-default" type="submit" onclick="searchPost($.trim($('#search-term').val()))"><i class="glyphicon glyphicon-search"></i></button>
								</div>
							</div>
						</form>
					</div>

				</div>
			</div>
		</nav>
		@if (ViewContext.RouteData.Values["controller"].ToString().ToLower() != "admin")
		{
			<div class="banner">
				<div class="container">
					<h2>@Helper.GetAppSettings().BlogName</h2>
					<h3>@Helper.GetAppSettings().SubBlogName</h3>
				</div>
			</div>
		}
		else
		{
			<div class="clearfix" style="height:50px;"></div>
		}
		<div class="container body-content">
			@RenderBody()
		</div>
		<div class="push"></div>
	</div>
	<div class="clearfix" style="height:10px;"></div>
	<!-- Footer -->
	<div class="footer">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 social-bar">
					<ul>
						<li><i class="fa fa-lg fa-facebook-square"></i></li>
						<li><i class="fa fa-lg fa-google-plus-square"></i></li>
						<li><i class="fa fa-lg fa-linkedin-square"></i></li>
						<li><i class="fa fa-lg fa-twitter-square"></i></li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<p>&copy; @DateTime.Now.Year - CyberBlog Developed By Biao Xiao</p>
				</div>

			</div>
		</div>
	</div>
	<!--/Footer -->
	
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("Scripts", required: false)
	<script>
		function searchPost(term) {
			var url = "/Search/"+term;
			$('#search-form').attr('action', url);
			$('#search-form').submit();
		}
	</script>
</body>
</html>

CyberBlog.Web/Views/Shared/_Tags.cshtml
@model IList<CyberBlog.ViewModel.TagViewModel>
<h4 class="side-bar">Tags</h4>
<ul class="list-unstyled list-inline">
	@if (Model.Count> 0)
	{
		foreach (var item in Model)
		{
			<li>
				<a href="/tag/@item.UrlSlug">@item.Tag.ToLower()</a>
			</li>
		}
	}
</ul>